"""add source_type to startup_source

Revision ID: 048299ae841b
Revises: 1ec48212cd2e
Create Date: 2026-04-01 09:23:22.993327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048299ae841b'
down_revision = '1ec48212cd2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startup_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startup_source', schema=None) as batch_op:
        batch_op.drop_column('source_type')

    # ### end Alembic commands ###
