"""add ai_revision_history

Revision ID: 0dae407b3532
Revises: 777d6f53b6d9
Create Date: 2026-03-31 13:23:27.914215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dae407b3532'
down_revision = '777d6f53b6d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_revision_history', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('ai_revision_history')

    # ### end Alembic commands ###
