"""add company_stage and spinoff_origin

Revision ID: 49c921a295e9
Revises: 7024a11e2baa
Create Date: 2026-03-31 08:50:56.548061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c921a295e9'
down_revision = '7024a11e2baa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_stage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('spinoff_origin', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('spinoff_origin')
        batch_op.drop_column('company_stage')

    # ### end Alembic commands ###
