"""add ai_analysis_failures counter

Revision ID: 49caaf89b017
Revises: 048299ae841b
Create Date: 2026-04-01 10:03:25.519301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49caaf89b017'
down_revision = '048299ae841b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_analysis_failures', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('ai_analysis_failures')

    # ### end Alembic commands ###
