"""add highlights field

Revision ID: 549537808745
Revises: 5b8500892c32
Create Date: 2026-03-26 15:37:21.720762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549537808745'
down_revision = '5b8500892c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlights', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('highlights')

    # ### end Alembic commands ###
