"""add insight fields and insight task type

Revision ID: 5b8500892c32
Revises: e5a1e5acc4cc
Create Date: 2026-03-26 13:27:43.218762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8500892c32'
down_revision = 'e5a1e5acc4cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insight_zh', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('insight_en', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('insight_en')
        batch_op.drop_column('insight_zh')

    # ### end Alembic commands ###
