"""add company ai_analysis fields

Revision ID: 777d6f53b6d9
Revises: 49c921a295e9
Create Date: 2026-03-31 12:49:27.837695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777d6f53b6d9'
down_revision = '49c921a295e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_analysis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_analysis_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('ai_analysis_at')
        batch_op.drop_column('ai_analysis')

    # ### end Alembic commands ###
