"""initial schema

Revision ID: e5a1e5acc4cc
Revises: 
Create Date: 2026-03-26 10:30:30.431386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a1e5acc4cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name_zh', sa.String(length=100), nullable=True),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('headquarters', sa.String(length=200), nullable=True),
    sa.Column('is_grenoble', sa.Boolean(), nullable=False),
    sa.Column('sector', sa.String(length=200), nullable=True),
    sa.Column('is_auto_created', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('llm_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('api_key_env_var', sa.String(length=200), nullable=True),
    sa.Column('api_base_url', sa.String(length=500), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('cost_per_1k_input', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('cost_per_1k_output', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('tasks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('feed_url', sa.String(length=500), nullable=True),
    sa.Column('feed_type', sa.Enum('rss', 'atom', 'html_scrape', name='feed_type_enum'), nullable=False),
    sa.Column('crawler_class', sa.String(length=200), nullable=True),
    sa.Column('category', sa.Enum('national', 'regional', 'institutional', name='source_category_enum'), nullable=False),
    sa.Column('crawl_frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active_user', sa.Boolean(), nullable=True),
    sa.Column('receive_daily_digest', sa.Boolean(), nullable=True),
    sa.Column('preferred_language', sa.Enum('fr', 'zh', 'en', name='language_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('title_fr', sa.String(length=500), nullable=False),
    sa.Column('title_zh', sa.String(length=500), nullable=True),
    sa.Column('title_en', sa.String(length=500), nullable=True),
    sa.Column('content_fr', sa.Text(), nullable=True),
    sa.Column('content_zh', sa.Text(), nullable=True),
    sa.Column('content_en', sa.Text(), nullable=True),
    sa.Column('summary_fr', sa.Text(), nullable=True),
    sa.Column('summary_zh', sa.Text(), nullable=True),
    sa.Column('summary_en', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=False),
    sa.Column('llm_processed', sa.Boolean(), nullable=False),
    sa.Column('llm_processed_at', sa.DateTime(), nullable=True),
    sa.Column('llm_provider', sa.String(length=100), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['news_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_article_external')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index('idx_crawled_at', ['crawled_at'], unique=False)
        batch_op.create_index('idx_published_at', ['published_at'], unique=False)

    op.create_table('crawl_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='crawl_status_enum'), nullable=True),
    sa.Column('articles_found', sa.Integer(), nullable=True),
    sa.Column('articles_new', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['news_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_log', schema=None) as batch_op:
        batch_op.create_index('idx_source_started', ['source_id', 'started_at'], unique=False)

    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_type', sa.Enum('daily_digest', 'keyword_alert', name='email_type_enum'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('sent', 'failed', name='email_status_enum'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'keyword', name='uq_user_keyword')
    )
    op.create_table('article_category',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'category_id')
    )
    op.create_table('article_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.Enum('positive', 'negative', 'neutral', name='sentiment_enum'), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('extracted_by', sa.Enum('llm', 'manual', 'rule', name='extraction_method_enum'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'company_id', name='uq_article_company')
    )
    with op.batch_alter_table('article_company', schema=None) as batch_op:
        batch_op.create_index('idx_company_sentiment', ['company_id', 'sentiment'], unique=False)

    op.create_table('llm_usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('translate', 'summarize', 'ner', 'sentiment', 'classify', name='llm_task_type_enum'), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['config_id'], ['llm_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_usage_log', schema=None) as batch_op:
        batch_op.create_index('idx_llm_usage_created', ['created_at'], unique=False)
        batch_op.create_index('idx_llm_usage_task', ['task_type', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_usage_log', schema=None) as batch_op:
        batch_op.drop_index('idx_llm_usage_task')
        batch_op.drop_index('idx_llm_usage_created')

    op.drop_table('llm_usage_log')
    with op.batch_alter_table('article_company', schema=None) as batch_op:
        batch_op.drop_index('idx_company_sentiment')

    op.drop_table('article_company')
    op.drop_table('article_category')
    op.drop_table('keyword_subscription')
    op.drop_table('email_log')
    with op.batch_alter_table('crawl_log', schema=None) as batch_op:
        batch_op.drop_index('idx_source_started')

    op.drop_table('crawl_log')
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index('idx_published_at')
        batch_op.drop_index('idx_crawled_at')

    op.drop_table('article')
    op.drop_table('user')
    op.drop_table('news_source')
    op.drop_table('llm_config')
    op.drop_table('company')
    op.drop_table('category')
    # ### end Alembic commands ###
