"""Seed the database with known Grenoble-area tech companies."""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from slugify import slugify
from app import create_app
from app.extensions import db
from app.models.company import Company

COMPANIES = [
    {
        'name': 'STMicroelectronics',
        'aliases': ['STMicro', 'ST Microelectronics', 'ST'],
        'website': 'https://www.st.com',
        'headquarters': 'Geneva / Crolles',
        'sector': 'Semiconductor',
        'is_grenoble': True,
        'company_stage': 'mature',
        'description': 'Major semiconductor company with large fabrication facility in Crolles near Grenoble.',
    },
    {
        'name': 'Schneider Electric',
        'aliases': ['Schneider'],
        'website': 'https://www.se.com',
        'headquarters': 'Rueil-Malmaison / Grenoble',
        'sector': 'Energy Management / IoT',
        'is_grenoble': True,
        'description': 'Global energy management and automation company, historically headquartered in Grenoble.',
    },
    {
        'name': 'Soitec',
        'aliases': [],
        'website': 'https://www.soitec.com',
        'headquarters': 'Bernin (Grenoble)',
        'sector': 'Semiconductor Materials',
        'is_grenoble': True,
        'description': 'SOI wafer and advanced semiconductor substrate manufacturer based near Grenoble.',
    },
    {
        'name': 'Lynred',
        'aliases': ['Sofradir'],
        'website': 'https://www.lynred.com',
        'headquarters': 'Grenoble',
        'sector': 'Infrared Detectors',
        'is_grenoble': True,
        'description': 'Infrared detector manufacturer for defense, space, and industrial applications.',
    },
    {
        'name': 'CEA-Leti',
        'aliases': ['CEA Leti', 'Leti', 'CEA'],
        'website': 'https://www.leti-cea.com',
        'headquarters': 'Grenoble',
        'sector': 'Research Institute',
        'is_grenoble': True,
        'description': 'Applied research institute for microelectronics and nanotechnology.',
    },
    {
        'name': 'Minalogic',
        'aliases': [],
        'website': 'https://www.minalogic.com',
        'headquarters': 'Grenoble',
        'sector': 'Tech Cluster',
        'is_grenoble': True,
        'description': 'Digital technology and semiconductor cluster in the Grenoble area.',
    },
    {
        'name': 'ESRF',
        'aliases': ['European Synchrotron'],
        'website': 'https://www.esrf.fr',
        'headquarters': 'Grenoble',
        'sector': 'Research Facility',
        'is_grenoble': True,
        'description': 'European Synchrotron Radiation Facility, world-leading light source.',
    },
    {
        'name': 'Inria',
        'aliases': ['INRIA'],
        'website': 'https://www.inria.fr',
        'headquarters': 'Grenoble (center)',
        'sector': 'Research Institute',
        'is_grenoble': True,
        'description': 'French national research institute for computer science and applied mathematics.',
    },
    {
        'name': 'ILL',
        'aliases': ['Institut Laue-Langevin'],
        'website': 'https://www.ill.eu',
        'headquarters': 'Grenoble',
        'sector': 'Research Facility',
        'is_grenoble': True,
        'description': 'International neutron research facility.',
    },
    {
        'name': 'Grenoble INP - UGA',
        'aliases': ['Grenoble INP', 'UGA'],
        'website': 'https://www.grenoble-inp.fr',
        'headquarters': 'Grenoble',
        'sector': 'University',
        'is_grenoble': True,
        'description': 'Engineering school and university, part of Universit\u00e9 Grenoble Alpes.',
    },
    {
        'name': 'Capgemini',
        'aliases': [],
        'website': 'https://www.capgemini.com',
        'headquarters': 'Paris (Grenoble office)',
        'sector': 'IT Services',
        'is_grenoble': True,
        'description': 'Major IT services company with significant Grenoble presence.',
    },
    {
        'name': 'Hewlett Packard Enterprise',
        'aliases': ['HPE', 'HP'],
        'website': 'https://www.hpe.com',
        'headquarters': 'Houston (Grenoble R&D)',
        'sector': 'Enterprise IT',
        'is_grenoble': True,
        'description': 'Major tech company with R&D center in Grenoble (formerly HP Labs).',
    },
    {
        'name': 'Allegro DVT',
        'aliases': ['Allegro'],
        'website': 'https://www.allegrodvt.com',
        'headquarters': 'Grenoble',
        'sector': 'Semiconductor IP',
        'is_grenoble': True,
        'company_stage': 'mature',
        'description': 'Video codec IP and semiconductor design company.',
    },
    # ── CEA-Leti Spin-offs ───────────────────────────────────────
    {
        'name': 'Kalray',
        'aliases': [],
        'website': 'https://www.kalray.eu',
        'headquarters': 'Grenoble',
        'sector': 'Semiconductor / AI Processors',
        'is_grenoble': True,
        'company_stage': 'scale-up',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Intelligent processor (MPPA) for data-intensive applications. CEA-Leti spin-off, listed on Euronext.',
    },
    {
        'name': 'Prophesee',
        'aliases': [],
        'website': 'https://www.prophesee.ai',
        'headquarters': 'Paris / Grenoble',
        'sector': 'Neuromorphic Vision',
        'is_grenoble': True,
        'company_stage': 'scale-up',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Event-based vision sensors (neuromorphic). CEA-Leti spin-off.',
    },
    {
        'name': 'Arteris',
        'aliases': ['Arteris IP'],
        'website': 'https://www.arteris.com',
        'headquarters': 'San Jose / Grenoble',
        'sector': 'Semiconductor IP',
        'is_grenoble': True,
        'company_stage': 'mature',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Network-on-Chip interconnect IP for SoCs. CEA-Leti spin-off, listed on Nasdaq.',
    },
    {
        'name': 'Dolphin Design',
        'aliases': ['Dolphin Integration'],
        'website': 'https://www.dolphin.fr',
        'headquarters': 'Grenoble',
        'sector': 'Semiconductor IP',
        'is_grenoble': True,
        'company_stage': 'mature',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Ultra-low-power SoC design and virtual prototyping platform. CEA-Leti spin-off.',
    },
    {
        'name': 'GreenWaves Technologies',
        'aliases': ['GreenWaves'],
        'website': 'https://greenwaves-technologies.com',
        'headquarters': 'Grenoble',
        'sector': 'AI / IoT Processors',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Ultra-low-power AI processors (GAP series) for IoT edge devices. CEA-Leti spin-off.',
    },
    {
        'name': 'Lancey Energy Storage',
        'aliases': ['Lancey'],
        'website': 'https://www.lancey.fr',
        'headquarters': 'Grenoble',
        'sector': 'Energy / CleanTech',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Smart electric radiator with integrated battery for energy management. CEA-Leti spin-off.',
    },
    {
        'name': 'Pixyl',
        'aliases': [],
        'website': 'https://www.pixyl.ai',
        'headquarters': 'Grenoble',
        'sector': 'MedTech / AI',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'Inria / UGA',
        'description': 'AI-powered medical imaging analysis for neurological diseases. Inria Grenoble spin-off.',
    },
    {
        'name': 'Microoled',
        'aliases': ['ActiveLook'],
        'website': 'https://www.microoled.net',
        'headquarters': 'Grenoble',
        'sector': 'Micro-displays / AR',
        'is_grenoble': True,
        'company_stage': 'scale-up',
        'spinoff_origin': 'CEA-Leti',
        'description': 'OLED micro-displays for smart glasses and AR. CEA-Leti spin-off.',
    },
    {
        'name': 'Aledia',
        'aliases': [],
        'website': 'https://www.aledia.com',
        'headquarters': 'Grenoble',
        'sector': 'Micro-LED / Displays',
        'is_grenoble': True,
        'company_stage': 'scale-up',
        'spinoff_origin': 'CEA-Leti',
        'description': '3D micro-LED display technology for next-gen screens. CEA-Leti spin-off.',
    },
    {
        'name': 'Linksium',
        'aliases': [],
        'website': 'https://www.linksium.fr',
        'headquarters': 'Grenoble',
        'sector': 'Tech Transfer / Incubator',
        'is_grenoble': True,
        'company_stage': 'mature',
        'description': 'Technology transfer and startup incubator for Grenoble ecosystem (UGA, CEA, CNRS).',
    },
    # ── CEA-Leti Startup Program (from programme-startup.aspx) ──
    {
        'name': 'Quobly',
        'aliases': [],
        'website': 'https://www.quobly.io',
        'headquarters': 'Grenoble',
        'sector': 'Quantum Computing',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Silicon-based qubit quantum computer. CEA-Leti spin-off.',
    },
    {
        'name': 'Aryballe',
        'aliases': [],
        'website': 'https://www.aryballe.com',
        'headquarters': 'Grenoble',
        'sector': 'Sensors / AI',
        'is_grenoble': True,
        'company_stage': 'scale-up',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Digital olfaction — electronic nose for odor sensing. CEA-Leti spin-off.',
    },
    {
        'name': 'Diabeloop',
        'aliases': ['DIABELOOP'],
        'website': 'https://www.diabeloop.com',
        'headquarters': 'Grenoble',
        'sector': 'MedTech / AI',
        'is_grenoble': True,
        'company_stage': 'scale-up',
        'spinoff_origin': 'CEA-Leti',
        'description': 'AI-driven automated insulin delivery for diabetes management. CEA-Leti spin-off.',
    },
    {
        'name': 'Scintil Photonics',
        'aliases': ['SCINTIL PHOTONICS'],
        'website': 'https://www.scintil-photonics.com',
        'headquarters': 'Grenoble',
        'sector': 'Photonics / Semiconductor',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Integrated lasers for silicon photonics. CEA-Leti spin-off.',
    },
    {
        'name': 'Primo1D',
        'aliases': [],
        'website': 'https://www.primo1d.com',
        'headquarters': 'Grenoble',
        'sector': 'IoT / RFID',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Miniaturized RFID tags integrated into textile yarn. CEA-Leti spin-off.',
    },
    {
        'name': 'Apix Analytics',
        'aliases': [],
        'headquarters': 'Grenoble',
        'sector': 'Sensors / Analytics',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'CEA-Leti',
        'description': 'In-situ gas and liquid analysis for industrial applications. CEA-Leti spin-off.',
    },
    {
        'name': 'Wise Integration',
        'aliases': [],
        'headquarters': 'Grenoble',
        'sector': 'Power Electronics',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Innovative power electronics solutions (GaN). CEA-Leti spin-off.',
    },
    {
        'name': 'SteerLight',
        'aliases': [],
        'headquarters': 'Grenoble',
        'sector': 'LiDAR / Automotive',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Next-gen LIDAR sensors for autonomous vehicles. CEA-Leti spin-off.',
    },
    {
        'name': 'Fluoptics',
        'aliases': [],
        'headquarters': 'Grenoble',
        'sector': 'MedTech / Imaging',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Fluorescence imaging for surgical guidance. CEA-Leti spin-off.',
    },
    {
        'name': 'Avalun',
        'aliases': [],
        'headquarters': 'Grenoble',
        'sector': 'MedTech / Diagnostics',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Portable biological analysis device for point-of-care testing. CEA-Leti spin-off.',
    },
    {
        'name': 'Remedee Labs',
        'aliases': [],
        'website': 'https://www.remedee.com',
        'headquarters': 'Grenoble',
        'sector': 'MedTech / Wearables',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Chronic pain relief via endorphin stimulation wearable. CEA-Leti spin-off.',
    },
    {
        'name': 'Kentyou',
        'aliases': [],
        'headquarters': 'Grenoble',
        'sector': 'IoT / Smart City',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Digital transformation platform for smart cities. CEA-Leti spin-off.',
    },
    {
        'name': 'Asygn',
        'aliases': [],
        'headquarters': 'Grenoble',
        'sector': 'Semiconductor / IC Design',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'CEA-Leti',
        'description': 'High-performance circuits for sensors, telecom, and AI. CEA-Leti spin-off.',
    },
    {
        'name': 'Arnano',
        'aliases': [],
        'headquarters': 'Grenoble',
        'sector': 'Nanotechnology',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Microscopic engraving for watchmaking and data archiving. CEA-Leti spin-off.',
    },
    {
        'name': 'Wormsensing',
        'aliases': [],
        'headquarters': 'Grenoble',
        'sector': 'Sensors / Vibration',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Vibration measurement sensors. CEA-Leti spin-off.',
    },
    {
        'name': 'Mag4Health',
        'aliases': [],
        'headquarters': 'Grenoble',
        'sector': 'MedTech / Imaging',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Accessible magnetoencephalography (MEG) for brain imaging. CEA-Leti spin-off.',
    },
    {
        'name': 'Diamsens',
        'aliases': [],
        'headquarters': 'Grenoble',
        'sector': 'Sensors / Environment',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'CEA-Leti',
        'description': 'In-situ water quality monitoring sensors. CEA-Leti spin-off.',
    },
    {
        'name': 'InjectPower',
        'aliases': ['INJECTPOWER'],
        'headquarters': 'Grenoble',
        'sector': 'MedTech / Energy',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Next-gen micro-batteries for implantable medical devices. CEA-Leti spin-off.',
    },
    {
        'name': 'Bag-Era',
        'aliases': [],
        'headquarters': 'Grenoble',
        'sector': 'Digital Systems',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Integration and supervision of heterogeneous digital systems. CEA-Leti spin-off.',
    },
    {
        'name': 'BAIO-DX',
        'aliases': [],
        'headquarters': 'Grenoble',
        'sector': 'MedTech / AI',
        'is_grenoble': True,
        'company_stage': 'startup',
        'spinoff_origin': 'CEA-Leti',
        'description': 'Rapid bacteria identification via holographic imaging and AI. CEA-Leti spin-off.',
    },
]


def seed():
    app = create_app()
    with app.app_context():
        for data in COMPANIES:
            slug = slugify(data['name'])
            existing = Company.query.filter_by(slug=slug).first()
            if existing:
                # Update new fields if they were added
                updated = False
                for field in ('company_stage', 'spinoff_origin'):
                    if field in data and data[field] and not getattr(existing, field, None):
                        setattr(existing, field, data[field])
                        updated = True
                if updated:
                    print(f'  Updated {data["name"]} (new fields)')
                else:
                    print(f'  Skipping {data["name"]} (already exists)')
                continue
            company = Company(slug=slug, **data)
            db.session.add(company)
            print(f'  Added: {data["name"]}')
        db.session.commit()
        print(f'\nDone. {Company.query.count()} companies in database.')


if __name__ == '__main__':
    seed()
